In [1]:
import pandas as pd


In [2]:
data=pd.read_csv("/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project/data/phisingData.csv")
data.head()

having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon  ...  popUpWidnow  Iframe  \
0                           -1        1  ...            1       1   
1                           -1        1  ...            1       1   
2                           -1        1  ...            1       1   
3                            1        1  ...            1       1   
4                           -1        1  ...           -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                  -1      -1  
1                       1                   1      -1  
2                       0                  -1      -1  
3                      -1                   1      -1  
4                       1                   1       1  

[5 rows x 31 columns]

In [3]:
json_data=data.to_dict(orient="records")
json_data

[{'having_IP_Address': -1,
  'URL_Length': 1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': -1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': -1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1,
  'URL_of_Anchor': -1,
  'Links_in_tags': 1,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': -1,
  'web_traffic': -1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 1,
  'Statistical_report': -1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1

In [4]:
json_data[0]

{'having_IP_Address': -1,
 'URL_Length': 1,
 'Shortining_Service': 1,
 'having_At_Symbol': 1,
 'double_slash_redirecting': -1,
 'Prefix_Suffix': -1,
 'having_Sub_Domain': -1,
 'SSLfinal_State': -1,
 'Domain_registeration_length': -1,
 'Favicon': 1,
 'port': 1,
 'HTTPS_token': -1,
 'Request_URL': 1,
 'URL_of_Anchor': -1,
 'Links_in_tags': 1,
 'SFH': -1,
 'Submitting_to_email': -1,
 'Abnormal_URL': -1,
 'Redirect': 0,
 'on_mouseover': 1,
 'RightClick': 1,
 'popUpWidnow': 1,
 'Iframe': 1,
 'age_of_domain': -1,
 'DNSRecord': -1,
 'web_traffic': -1,
 'Page_Rank': -1,
 'Google_Index': 1,
 'Links_pointing_to_page': 1,
 'Statistical_report': -1,
 'Result': -1}

In [5]:
uri="mongodb+srv://iamsanju0707:DWVLL5PqpDwtXOjl@cluster.mongodb.net/Network_Security_Database?retryWrites=true&w=majority"

In [6]:
# from pymongo import MongoClient
# client=MongoClient(uri)


In [7]:
import os
from dotenv import load_dotenv
load_dotenv()
username=os.getenv("MONGODB_USERNAME")
password=os.getenv("MONGODB_PASSWORD")
uri=os.getenv("MONGODB_URI")
print(uri)

mongodb+srv://iamsanju0707:DWVLL5PqpDwtXOjl@cluster0.4ul2y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0


In [8]:
# import os
# from pymongo import MongoClient

# username = os.getenv("MONGO_USER")  # Ensure this is set
# password = os.getenv("MONGO_PASS")  # Ensure this is set

# connection_string = f"mongodb+srv://{username}:{password}@cluster.mongodb.net/<dbname>?retryWrites=true&w=majority"
# client = MongoClient(connection_string)

In [9]:
from pymongo import MongoClient
uri = "mongodb+srv://iamsanju0707:DWVLL5PqpDwtXOjl@cluster0.4ul2y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

In [10]:
uri

'mongodb+srv://iamsanju0707:DWVLL5PqpDwtXOjl@cluster0.4ul2y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'

In [11]:
client=MongoClient(uri)

In [12]:
client

MongoClient(host=['cluster0-shard-00-01.4ul2y.mongodb.net:27017', 'cluster0-shard-00-02.4ul2y.mongodb.net:27017', 'cluster0-shard-00-00.4ul2y.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', appname='Cluster0', authsource='admin', replicaset='atlas-11f97w-shard-0', tls=True)

In [13]:
import pandas as pd

In [14]:
db=client["Network_Security_Database"]


In [15]:
collection=db["NetworkData"]

In [16]:
data=pd.DataFrame(list(collection.find()))

In [17]:
train_data=pd.read_csv("/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project/artifacts/data_ingestion/ingested/train.csv")
test_data=pd.read_csv("/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project/artifacts/data_ingestion/ingested/test.csv")

In [18]:
from scipy.stats import ks_2samp

In [19]:
ks_2samp(train_data,test_data,alternative='two-sided',method="auto")

KstestResult(statistic=array([0.01040253, 0.01017639, 0.01311624, 0.        , 0.00972411,
       0.00452284, 0.01379466, 0.00995025, 0.00011307, 0.00135685,
       0.00361827, 0.00723654, 0.00282678, 0.01062867, 0.00734962,
       0.00293985, 0.019109  , 0.00067843, 0.00972411, 0.00395749,
       0.00237449, 0.00305292, 0.00248756, 0.00723654, 0.00033921,
       0.00293985, 0.00407056, 0.00384441, 0.0027137 , 0.00452284,
       0.00870647]), pvalue=array([0.99032082, 0.99256112, 0.91879625, 1.        , 0.99585794,
       1.        , 0.88659109, 0.99439087, 1.        , 1.        ,
       1.        , 0.99998365, 1.        , 0.9876237 , 0.99997603,
       1.        , 0.5343963 , 1.        , 0.99585794, 1.        ,
       1.        , 1.        , 1.        , 0.99998365, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.99923065]), statistic_location=array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        0.,  0.,  0., -1., -1.,  

In [20]:
import numpy as np

In [21]:
report={}
status=None
for column in train_data.columns:
    d1=train_data[column]
    d2=test_data[column]
    # print(f"this si d1: {d1}")
    # print(f"This is d2: {d2}")
    is_same_dist=ks_2samp(d1,d2)
    if is_same_dist.pvalue>0.05:
        status=True
    else:
        status=False
    report.update({column:{
        "report_status":status,
        "p_value":float(is_same_dist.pvalue)
    }})

In [22]:
report

{'having_IP_Address': {'report_status': True, 'p_value': 0.9903208205295254},
 'URL_Length': {'report_status': True, 'p_value': 0.9925611176019148},
 'Shortining_Service': {'report_status': True, 'p_value': 0.918796249345484},
 'having_At_Symbol': {'report_status': True, 'p_value': 1.0},
 'double_slash_redirecting': {'report_status': True,
  'p_value': 0.9958579353974752},
 'Prefix_Suffix': {'report_status': True, 'p_value': 0.999999999999956},
 'having_Sub_Domain': {'report_status': True, 'p_value': 0.8865910920599936},
 'SSLfinal_State': {'report_status': True, 'p_value': 0.9943908690886974},
 'Domain_registeration_length': {'report_status': True, 'p_value': 1.0},
 'Favicon': {'report_status': True, 'p_value': 1.0},
 'port': {'report_status': True, 'p_value': 1.0},
 'HTTPS_token': {'report_status': True, 'p_value': 0.9999836499887566},
 'Request_URL': {'report_status': True, 'p_value': 1.0},
 'URL_of_Anchor': {'report_status': True, 'p_value': 0.9876237011526984},
 'Links_in_tags': {

In [23]:
from sklearn.pipeline import Pipeline

In [24]:
data.head()

_id  having_IP_Address  URL_Length  \
0  6773889ffdcea6f471ae9d92                  1          -1   
1  6773889ffdcea6f471ae9da0                  1          -1   
2  6773889ffdcea6f471ae9da1                  1          -1   
3  6773889ffdcea6f471ae9dc1                  1          -1   
4  6773889ffdcea6f471ae9dcb                 -1          -1   

   Shortining_Service  having_At_Symbol  double_slash_redirecting  \
0                  -1                 1                        -1   
1                   1                 1                         1   
2                   1                 1                         1   
3                   1                 1                        -1   
4                  -1                 1                         1   

   Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0              1                 -1               1   
1             -1                 -1              -1   
2             -1                  0               0   
3             -1                  1              -1   
4             -1                  0               0   

   Domain_registeration_length  ...  popUpWidnow  Iframe  age_of_domain  \
0                           -1  ...            1       1             -1   
1                            1  ...           -1       1             -1   
2                            1  ...           -1       1              1   
3                            1  ...            1       1             -1   
4                           -1  ...            1       1              1   

   DNSRecord  web_traffic  Page_Rank  Google_Index  Links_pointing_to_page  \
0         -1            1         -1             1                      -1   
1         -1            1         -1             1                      -1   
2         -1           -1         -1             1                       0   
3         -1            1         -1             1                       1   
4         -1           -1         -1             1                       0   

   Statistical_report  Result  
0                   1       1  
1                  -1      -1  
2                  -1      -1  
3                   1      -1  
4                  -1      -1  

[5 rows x 32 columns]

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   _id                          11055 non-null  object
 1   having_IP_Address            11055 non-null  int64 
 2   URL_Length                   11055 non-null  int64 
 3   Shortining_Service           11055 non-null  int64 
 4   having_At_Symbol             11055 non-null  int64 
 5   double_slash_redirecting     11055 non-null  int64 
 6   Prefix_Suffix                11055 non-null  int64 
 7   having_Sub_Domain            11055 non-null  int64 
 8   SSLfinal_State               11055 non-null  int64 
 9   Domain_registeration_length  11055 non-null  int64 
 10  Favicon                      11055 non-null  int64 
 11  port                         11055 non-null  int64 
 12  HTTPS_token                  11055 non-null  int64 
 13  Request_URL                  11

In [26]:
data.shape

(11055, 32)

In [27]:
data=data.drop_duplicates()

In [28]:
data.shape

(11055, 32)

In [29]:
data["Result"].value_counts()

Result
 1    6157
-1    4898
Name: count, dtype: int64

In [30]:
data["Result"].replace(-1,0,inplace=True)

/var/folders/sn/kf4x3ygj0tg81pp8_fswhmp00000gn/T/ipykernel_39053/3748885520.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Result"].replace(-1,0,inplace=True)


In [31]:
data["Result"].value_counts()

Result
1    6157
0    4898
Name: count, dtype: int64

In [32]:
from src.utils.common import read_yaml
from src.Constant.training_pipeline import DATA_TRANSFORMATION_PARAMS_FILE_PATH
from pathlib import Path
print(DATA_TRANSFORMATION_PARAMS_FILE_PATH)
# read_yaml(Path(DATA_TRANSFORMATION_PARAMS_FILE_PATH))

/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project/params.yaml


In [33]:
import os
os.chdir("..")

In [34]:
pwd

'/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project'

In [35]:
from src.utils.common import read_yaml
from src.Constant.training_pipeline import DATA_TRANSFORMATION_PARAMS_FILE_PATH
from pathlib import Path
print(DATA_TRANSFORMATION_PARAMS_FILE_PATH)
params=read_yaml(Path(DATA_TRANSFORMATION_PARAMS_FILE_PATH))

/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project/params.yaml
2025-01-09 12:48:55,874 - INFO -common - Yaml file has been read Successfully. 


In [36]:
knn_params=dict(params["knn_imputer_params"])
knn_params

{'n_neighbors': 3, 'weights': 'uniform', 'metric': 'nan_euclidean'}

In [37]:
from sklearn.impute import KNNImputer
knnimputer=KNNImputer(**knn_params)

In [38]:
knnimputer

KNNImputer(n_neighbors=3)

In [39]:
from sklearn.pipeline import Pipeline
preprocessor=Pipeline(steps=[
    ("imputer",knnimputer)
])

In [40]:
preprocessor

Pipeline(steps=[('imputer', KNNImputer(n_neighbors=3))])

In [41]:
from sklearn.preprocessing import StandardScaler
standard_scaler=StandardScaler()


In [42]:
preprocessor.steps.append(
   ( "standard_scaler",standard_scaler)
)

In [43]:
preprocessor

Pipeline(steps=[('imputer', KNNImputer(n_neighbors=3)),
                ('standard_scaler', StandardScaler())])

In [44]:
## Model trainer Portion

In [45]:
from src.utils.common import load_array,load_object


In [46]:
train_data=load_array("artifacts/data_transformation/transformed/train.npy")
test_data=load_array("artifacts/data_transformation/transformed/test.npy")

In [47]:
X_train=train_data[:,:-1]
X_train

array([[ 1., -1.,  1., ...,  1.,  0.,  1.],
       [ 1., -1.,  1., ..., -1.,  1.,  1.],
       [-1., -1.,  1., ...,  1.,  1.,  1.],
       ...,
       [-1., -1.,  1., ...,  1., -1.,  1.],
       [ 1., -1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  0.,  1., ...,  1.,  0., -1.]], shape=(8844, 30))

In [48]:
y_train=train_data[:,-1]
y_train

array([1., 0., 1., ..., 0., 1., 0.], shape=(8844,))

In [49]:
X_test=test_data[:,:-1]
y_test=test_data[:,-1]

In [50]:
from src.Constant.training_pipeline import DATA_TRANSFORMATION_PARAMS_FILE_PATH

In [51]:
params=read_yaml(Path(DATA_TRANSFORMATION_PARAMS_FILE_PATH))

2025-01-09 12:48:56,047 - INFO -common - Yaml file has been read Successfully. 


In [52]:
params

DotMap(knn_imputer_params=DotMap(n_neighbors=3, weights='uniform', metric='nan_euclidean'), models=DotMap(Random_Forest='RandomForestClassifier(verbose=1)', Decision_Tree='DecisionTreeClassifier()', Gradient_Boosting='GradientBoostingClassifier(verbose=1)', Logistic_Regression='LogisticRegression(verbose=1)', AdaBoost='AdaBoostClassifier()'), models_params=DotMap(Random_Forest=DotMap(criterion=['gini', 'entropy'], max_features=['sqrt', 'log2'], n_estimators=[8, 16, 32]), Decision_Tree=DotMap(splitter=['best', 'random'], criterion=['gini', 'entropy'], max_features=['sqrt', 'log2']), Gradient_Boosting=DotMap(loss=['log_loss', 'exponential'], learning_rate=[0.1, 0.05], subsample=[0.6, 0.7]), Logistic_Regression=DotMap(), AdaBoost=DotMap(learning_rate=[0.1, 0.01], n_estimators=[8, 16])), _ipython_display_=DotMap(), _repr_mimebundle_=DotMap())

In [53]:
models=params["models"]
models=dict(models)
models

{'Random_Forest': 'RandomForestClassifier(verbose=1)',
 'Decision_Tree': 'DecisionTreeClassifier()',
 'Gradient_Boosting': 'GradientBoostingClassifier(verbose=1)',
 'Logistic_Regression': 'LogisticRegression(verbose=1)',
 'AdaBoost': 'AdaBoostClassifier()'}

In [54]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

In [55]:
for i in range(len(list(models.items()))):
    model_name,model=list(models.items())[i]
    models_params=params["models_params"]
    # print(model_name)
    # print(models_params[model_name])
    param_grid=models_params[model_name]
    model=eval(model)
    print(model,param_grid)
    # model.fit(X_train,y_train)
    # model.fit(X_train,y_train)
    # print(model)
    grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring="accuracy", verbose=1, n_jobs=-1)

    #fit the model
    grid_search.fit(X_train, y_train)

    # Best hyperparameters
    print("Best Hyperparameters:", grid_search.best_params_)

    # Best estimator
    best_model = grid_search.best_estimator_

    # Evaluate the model
    y_pred = best_model.predict(X_test)
    print("Test Accuracy:", accuracy_score(y_test, y_pred))

print(f"this is the best model{best_model}")



RandomForestClassifier(verbose=1) DotMap(criterion=['gini', 'entropy'], max_features=['sqrt', 'log2'], n_estimators=[8, 16, 32])
Fitting 5 folds for each of 12 candidates, totalling 60 fits
Best Hyperparameters: {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 32}
Test Accuracy: 0.9674355495251018
DecisionTreeClassifier() DotMap(splitter=['best', 'random'], criterion=['gini', 'entropy'], max_features=['sqrt', 'log2'])
Fitting 5 folds for each of 8 candidates, totalling 40 fits
Best Hyperparameters: {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'best'}
Test Accuracy: 0.9561284486657621
GradientBoostingClassifier(verbose=1) DotMap(loss=['log_loss', 'exponential'], learning_rate=[0.1, 0.05], subsample=[0.6, 0.7])
Fitting 5 folds for each of 8 candidates, totalling 40 fits
      Iter       Train Loss      OOB Improve   Remaining Time 
      Iter       Train Loss      OOB Improve   Remaining Time 
      Iter       Train Loss      OOB Improve   Remaining Time 
      

 This problem is unconstrained.
 This problem is unconstrained.
 This problem is unconstrained.
 This problem is unconstrained.
 This problem is unconstrained.
 This problem is unconstrained.


RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           31     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  6.93147D-01    |proj g|=  3.37178D-01
Best Hyperparameters: {}

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   31     32     37      1     0     0   9.022D-05   1.822D-01
  F =  0.18222290021061738     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
Test Accuracy: 0.9258254183627318
AdaBoostClassifier() DotMap(learning_rate=[0.1, 0.01], n_estimators=[8, 16])
Fitting 5 folds for each of 4 candidates, totalling 20 fit

In [56]:
model_report={'Random_Forest': 0.9710538218000905, 'Decision_Tree': 0.9552238805970149, 'Gradient_Boosting': 0.9434644957033017, 'Logistic_Regression': 0.9185888738127544, 'AdaBoost': 0.8815015829941203}

In [57]:
model_report

{'Random_Forest': 0.9710538218000905,
 'Decision_Tree': 0.9552238805970149,
 'Gradient_Boosting': 0.9434644957033017,
 'Logistic_Regression': 0.9185888738127544,
 'AdaBoost': 0.8815015829941203}

In [58]:

best_score=max([  score for score in model_report.values()])
best_score


0.9710538218000905

In [59]:
best_model_name=[ model_name for model_name,model_score in model_report.items() if model_score==best_score ][0]
best_model_name


'Random_Forest'

In [60]:
best_model=eval([ model for model_name,model in models.items() if model_name==best_model_name][0])
best_model

RandomForestClassifier(verbose=1)

In [61]:
best_model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 1,
 'warm_start': False}

In [62]:
model=load_object("artifacts/model_trainer/trained_model/model.pkl")

2025-01-09 12:49:02,952 - INFO -common - Object has been save to artifacts/model_trainer/trained_model/model.pkl


In [63]:
model

RandomForestClassifier(verbose=1)

In [81]:
X_train.shape

(8844, 30)

In [92]:
c=pd.DataFrame(X_train[0]).T
c.shape

(1, 30)

In [93]:
model.predict(c)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s


array([1.])

In [64]:
new_input=[1,-1,1,1,1,1,-1,1,-1,-1,-1,1,1,0,1,-1,-1,1,0,1,1,-1,-1,1,-1,1,-1,1,1,-1]

In [65]:
new_input=np.array(new_input)
new_input.ndim

1

In [66]:

if new_input.ndim == 1:
    X = np.expand_dims(new_input, axis=1)

In [67]:
X.ndim

2

In [73]:
X.shape

(30, 1)

In [94]:
from src.utils.ml_utils.model import NetworkModel


In [100]:
obj=NetworkModel(pp,model)
obj.predict(c)

/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project/myenv/lib/python3.12/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNNImputer was fitted with feature names
  warnings.warn(
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s


array([1.])

In [98]:
pp=load_object("artifacts/data_transformation/transformed/transformed_object/preprocessor.pkl")
pp

2025-01-09 13:15:56,451 - INFO -common - Object has been save to artifacts/data_transformation/transformed/transformed_object/preprocessor.pkl


Pipeline(steps=[('imputer', KNNImputer(n_neighbors=3))])

In [99]:
pp.transform(c)

/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project/myenv/lib/python3.12/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNNImputer was fitted with feature names
  warnings.warn(


array([[ 1., -1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1.,
         0.,  1., -1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        -1.,  1.,  0.,  1.]])

In [69]:
pwd

'/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project'

In [70]:
valid_train=pd.read_csv("/Users/sanju/Documents/DS/MLOps/MLOps_Projects/Network_Security_Project/artifacts/data_validation/valid_data/train.csv")
valid_train

having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                    -1          -1                   1                -1   
1                    -1          -1                   1                -1   
2                     1          -1                   1                 1   
3                    -1          -1                   1                 1   
4                     1           1                   1                -1   
...                 ...         ...                 ...               ...   
8839                  1           1                  -1                 1   
8840                  1           1                   1                 1   
8841                  1          -1                  -1                 1   
8842                  1          -1                   1                -1   
8843                  1          -1                   1                 1   

      double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  \
0                            1             -1                  0   
1                           -1             -1                  0   
2                            1              1                 -1   
3                            1             -1                  1   
4                            1             -1                  1   
...                        ...            ...                ...   
8839                         1             -1                  1   
8840                         1             -1                  0   
8841                        -1              1                  1   
8842                         1              1                  1   
8843                         1              1                 -1   

      SSLfinal_State  Domain_registeration_length  Favicon  ...  popUpWidnow  \
0                  0                            1        1  ...           -1   
1                 -1                            1       -1  ...           -1   
2                  1                           -1       -1  ...           -1   
3                  0                           -1        1  ...            1   
4                  1                            1        1  ...            1   
...              ...                          ...      ...  ...          ...   
8839              -1                           -1        1  ...            1   
8840              -1                           -1        1  ...            1   
8841               1                           -1        1  ...            1   
8842               1                           -1       -1  ...           -1   
8843               1                           -1        1  ...            1   

      Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0         -1             -1          1           -1          1             1   
1         -1             -1          1           -1          1             1   
2         -1              1         -1            1         -1             1   
3          1             -1          1           -1         -1             1   
4          1             -1          1           -1         -1             1   
...      ...            ...        ...          ...        ...           ...   
8839       1             -1         -1           -1         -1            -1   
8840       1             -1          1            1         -1             1   
8841       1              1         -1            1         -1             1   
8842       1              1          1           -1         -1             1   
8843       1             -1         -1            1         -1             1   

      Links_pointing_to_page  Statistical_report  Result  
0                          0                   1      -1  
1                          0                  -1      -1  
2                          1                  -1       1  
3                          1                   1      -1  
4                         -1                   

In [71]:
X_valid_train=valid_train.drop("Result",axis=1)

In [72]:
preprocessor=load_object("artifacts/data_transformation/transformed/transformed_object/preprocessor.pkl")

2025-01-09 11:10:53,235 - INFO -common - Object has been save to artifacts/data_transformation/transformed/transformed_object/preprocessor.pkl


In [78]:
preprocessor.transform(X_valid_train)

array([[-1., -1.,  1., ...,  1.,  0.,  1.],
       [-1., -1.,  1., ...,  1.,  0., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       ...,
       [ 1., -1., -1., ...,  1.,  1.,  1.],
       [ 1., -1.,  1., ...,  1.,  0.,  1.],
       [ 1., -1.,  1., ...,  1., -1.,  1.]], shape=(8844, 30))

In [74]:
X

array([[ 1],
       [-1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [-1],
       [-1],
       [-1],
       [ 1],
       [ 1],
       [ 0],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [ 0],
       [ 1],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [-1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [-1]])